language: python
python:
  - 3.9
install:
  - pip install -q pipenv  codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro_tardelli --cov=libpythonpro_tardelli
after_success:
  - codecov