name: Python application

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: install dependencies
        run: pip install -q pipenv  codecov
        run: pipenv sync --dev
      - name: flake8
        run: flake8 .
      - name: pytest
        run: pytest libpythonpro_tardelli --cov=libpythonpro_tardelli
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fall_ci_if_error: true